# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-07 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 16, 33, 34, 144000), verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
    ]
